version: '3'
services:
  crew-ai:
    network_mode: host
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./output:/app/output
      - ./files:/app/files
      - ./knowledge:/app/knowledge
    environment:
      - APP=job
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - ANTHROPIC_MODEL=claude-3-7-sonnet-20250219
      - SERPER_API_KEY
  lint:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./output:/app/output
      - ./files:/app/files
      - ./knowledge:/app/knowledge
      - ./.pylintrc:/app/.pylintrc
    command: pylint /app/src
  black:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./.pylintrc:/app/.pylintrc
    command: black /app/src